### ISSUE TITLE
@ckb-ccc/ccc Error:code: 'ERR_REQUIRE_ESM' At @joyid+ckb@0.0.11_typescript@5.5.3/node_modules/@joyid/ckb/dist/index.js

### ISSUE THREAD

**Issue by mrqinxd** [ckb-ecofund/ccc#14]
var _ckbsdkutils = require('@nervosnetwork/ckb-sdk-utils');
At
node_modules/.pnpm/@joyid+ckb@0.0.11_typescript@5.5.3/node_modules/@joyid/ckb/dist/index.js:19

and

node_modules/.pnpm/@joyid+ckb@1.0.0_typescript@5.5.3/node_modules/@joyid/ckb/dist/index.js:15

Is there a type script version available？

**Comment by Hanssen0** [comment]
> var _ckbsdkutils = require('@nervosnetwork/ckb-sdk-utils');

Hi! Thank you for your feedback!

This problem is introduced by the `@nervosnetwork/ckb-sdk-utils` from the `@joyid/ckb`. We will contact the JoyID team to upgrade the package's version to fix this problem.

**Comment by Hanssen0** [comment]
https://github.com/nervina-labs/joyid-sdk-js/pull/38

**Comment by Hanssen0** [comment]
Upgraded at https://github.com/ckb-ecofund/ccc/commit/1897de3128b438ed04e954c40976739b0f8ec585 .
Published at v0.10.0-alpha.5, please check.

**Comment by mrqinxd** [comment]
Thank you for your reply but after I update to 0.0.10-alpha.5 (or even 0.0.10-alpha.9), the problem remains

Error：
.pnpm/@joyid+ckb@1.0.1_typescript@5.5.3/node_modules/@joyid/ckb/dist/index.js:15
var _ckbsdkutils = require('@nervosnetwork/ckb-sdk-utils'); var ckbUtils = _interopRequireWildcard(_ckbsdkutils);

I think this is another similar problem

**Comment by mrqinxd** [comment]
I use @ckb-ccc/core and it works but @ckb-ccc/ccc doesn't. Thank you

**Comment by mrqinxd** [comment]
Hope to add joyID verifyMessage as soon as possible, thanks

**Comment by Hanssen0** [comment]
> I use @ckb-ccc/core and it works but @ckb-ccc/ccc doesn't. Thank you

Got it. The problem still exists on CKB SDK JS. We will contact them for this.

**Comment by Hanssen0** [comment]
> Hope to add joyID verifyMessage as soon as possible, thanks

Yes. It will be added back to CCC as soon as the problem solved.

**Comment by Hanssen0** [comment]
Problem fixed in CKB SDK JS version 0.109.3. verifyMessageJoyId support added back to CCC on https://github.com/ckb-ecofund/ccc/commit/19a2ae5d1b314770fd900e0a2f980eb6e695ed33
Please check.

**Comment by mrqinxd** [comment]
good!thanks~
