### ISSUE TITLE
The `package.json` in the demo is missing `@ckb-ccc/connector`

### ISSUE THREAD

**Issue by sunchengzhu** [ckb-ecofund/ccc#16]
Following the instructions in the [README](https://github.com/ckb-ecofund/ccc/tree/master/packages/demo#getting-started), after running `yarn install` and then `yarn dev`, clicking on http://localhost:3000 results in the following error:

```
sunchengzhu@sunchengzhudeMac-Studio demo % yarn dev
yarn run v1.22.19
$ next dev
  ▲ Next.js 14.2.2
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 2.1s
 ○ Compiling / ...
 ⨯ ./node_modules/@ckb-ccc/connector-react/dist/barrel.js:1:1
Module not found: Can't resolve '@ckb-ccc/connector/barrel'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@ckb-ccc/connector-react/dist/index.js
./app/page.tsx
 ⨯ ./node_modules/@ckb-ccc/connector-react/dist/barrel.js:1:1
Module not found: Can't resolve '@ckb-ccc/connector/barrel'

https://nextjs.org/docs/messages/module-not-found
```
After additionally running `yarn add @ckb-ccc/connector -D`, it works correctly.

**Comment by 15168316096** [comment]
you can use pnpm install instead of yarn？

**Comment by Hanssen0** [comment]
Hi! CCC used `pnpm` to manage workspaces. It seems `yarn` didn't handle dependencies from other `pnpm` workspaces correctly.
Could you please try again using `pnpm` and see if the problem still exists?

**Comment by sunchengzhu** [comment]
Thank you both for your responses! @Hanssen0 @15168316096 

I previously mistakenly treated each directory under `packages` as standalone and executable projects. I executed `pnpm install && pnpm run build` in the root directory of `ccc`, and then entered the `demo` to run `pnpm dev`. I no longer encountered the 'Module not found' issue."
