### ISSUE TITLE
As an user, we want to have "switchNetwork" function inside CCC instead of calling window

### ISSUE THREAD

**Issue by trongdth** [ckb-ecofund/ccc#18]

**Comment by Hanssen0** [comment]
Could you please describe in detail what you want here? Like switching the network without disconnecting?

**Comment by trongdth** [comment]
Hi @Hanssen0 

We now detect which provider is connected to our dApp and then call the `switchNetwork` function. For example:

- If UTXO Global Wallet is connected, the dApp uses `window.utxoGlobal.switchNetwork(network)`.
- If Unisat is connected, the dApp uses `unisat.switchNetwork(network)`.

I think this process takes time and is not convenient for the dApp because we are already using CCC. Is there any exposure in a React hook that we can use to call the `switchNetwork` function instead?

**Comment by Hanssen0** [comment]
CCC switch the network when our users connect to a wallet. For example, for the UniSat Signer:
https://github.com/ckb-ecofund/ccc/blob/0a1f1d48b6b99481794e693637ce21eb65c6da8e/packages/uni-sat/src/signer.ts#L110-L113
Also, by implementing the onReplaced method, the Signer can notify CCC connector to update the Signer status:
https://github.com/ckb-ecofund/ccc/blob/0a1f1d48b6b99481794e693637ce21eb65c6da8e/packages/uni-sat/src/signer.ts#L115-L130

**Comment by trongdth** [comment]
Hi @Hanssen0,

I mean on the dApp side, once the user clicks on the network switching button to switch between CKB Testnet and Mainnet, for example, it would be great to use the switchNetwork function of CCC, I think.

**Comment by yixyxiu** [comment]
I believe allowing users to freely switch between the mainnet and testnet within the dApp may not be ideal.

The mainnet version, which is stable and thoroughly tested, should be the default for users. For those who need access to the testnet, perhaps for participation during the application's testnet phase, I recommend deploying a separate testnet page, such as **dev.xxxx.io**. Just my two cents.

**Comment by Hanssen0** [comment]
https://github.com/ckb-ecofund/ccc/pull/25 is working on switching network.

**Comment by Hanssen0** [comment]
> The mainnet version, which is stable and thoroughly tested, should be the default for users.

I personally don't think these two ideas conflict. We can have two deployments, one for stable and another for preview. Meanwhile, users can switch networks on both deployments (Maybe default to mainnet on the stable version and testnet on the preview version).

Compared with the original approach, this allows cautious users to test the application with the same code before using real assets. Notice that this is just an option for developers. It's totally OK to hide/remove the switcher for better UX.

**Comment by Hanssen0** [comment]
#25
