### ISSUE TITLE
How to listen the onClose event of popup？

### ISSUE THREAD

**Issue by qinhua** [ckb-ecofund/ccc#77]
I need to reset certain states when the CCC pop-up window closes, but after reviewing the documentation and source code, I couldn't find the relevant configuration items

**Comment by Hanssen0** [comment]
Hi!
Which package are you using? `@ckb-ccc/connector` or `@ckb-ccc/connector-react`?

**Comment by qinhua** [comment]
> Hi! Which package are you using? `@ckb-ccc/connector` or `@ckb-ccc/connector-react`?

@ckb-ccc/connector-react

**Comment by Hanssen0** [comment]
> @ckb-ccc/connector-react

I got you. Currently, the component in this package doesn't provide the state of opening. Please check #78 and see if the new properties returned from the useCCC hook meet your needs.

**Comment by qinhua** [comment]
> > @ckb-ccc/connector-react
> 
> I got you. Currently, the component in this package doesn't provide the state of opening. Please check #78 and see if the new properties returned from the useCCC hook meet your needs.



> > @ckb-ccc/connector-react
> 
> I got you. Currently, the component in this package doesn't provide the state of opening. Please check #78 and see if the new properties returned from the useCCC hook meet your needs.

Enough, so I can do it by listening  `isOpen`  👍🏻👍🏻👍🏻

**Comment by Hanssen0** [comment]
Added in the `@ckb-ccc/connector-react` version 0.0.17-alpha.7, see #79
