### ISSUE TITLE
How to customize the order of the wallet list?

### ISSUE THREAD

**Issue by qinhua** [ckb-ecofund/ccc#80]
Hello, may I ask if our SDK currently provides a method to configure the order of the wallet list? 
Cause in practical use, we often need to define the order.

<img width="250" src="https://ice.frostsky.com/2024/10/17/11a1adf9eaf4b918e36a935f4284f32a.png" alt="11a1adf9eaf4b918e36a935f4284f32a.png" border="0">

**Comment by Hanssen0** [comment]
[`ccc.Provider`](https://docs.ckbccc.com/functions/_ckb_ccc_connector_react.index.ccc.Provider.html) allows devs to use a custom `signersController` instance, which can be used to control the wallet list. More details can be found on [`ccc.SignersController`](https://docs.ckbccc.com/classes/_ckb_ccc_ccc.index.ccc.SignersController.html).

For this specified question, it's possible to override the `SignersController.refresh` method and wrap the `onUpdate` handler to modify the wallet list.
